### ISSUE TITLE
部分命令执行失败

### ISSUE THREAD

**Issue by random665** [0nise/shell-plus#1]
ping命令响应乱编码
![image](https://user-images.githubusercontent.com/42052333/70965664-6ac58180-20cb-11ea-8b68-83f5e1c90f17.png)

部分命令执行失败
![image](https://user-images.githubusercontent.com/42052333/70965636-4e294980-20cb-11ea-8312-549715cddde3.png)

操作环境
win10  
java version "1.8.0_121"

**Comment by 0nise** [comment]
乱码BUG已修复，部分命令失效，下一个版本调整。
