### ISSUE TITLE
没看懂这个服务端和客户端的ip分别是什么？

### ISSUE THREAD

**Issue by xsshim** [0nise/shell-plus#2]

**Comment by xsshim** [comment]
还有就是进去cmd之后为什么连 dir 这种命令都无法执行的？ 显示 DIR execute error,msg: not found commond

**Comment by 0nise** [comment]
服务端的ip的主要是用来区分IP是否为内外网的，考虑到工具的特殊性目前工具兼容linux、mac比较强windows的优化在下一版本开始。
